name: Angular CD with EC2

on:
  workflow_run:
    workflows: ["Angular CI"]
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: sudo docker pull sheldrakecreator/ecommrepo:clientside
      - name: Delete Old Docker Container
        run: sudo docker rm -f angular-frontend || true

      - name: Stop and remove existing container
        run: |
          if [ "$(sudo docker ps -q -f name=angular-frontend)" ]; then
            sudo docker stop angular-frontend
            sudo docker rm angular-frontend
          fi
      - name: Run New Docker Container
        run: |
          sudo docker run -d --name angular-frontend --network myNetwork -p 80:80 -p 443:443  sheldrakecreator/ecommrepo:clientside

      - name: Verify Docker Container is Running
        run: sudo docker ps -a | grep angular-frontend