name: Deploy EcommApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Pull latest Docker images
        run: |
          docker pull sheldrakecreator/ecommrepo:clientside
          docker pull sheldrakecreator/ecommrepo:server

      - name: Stop and remove old containers
        run: |
          docker-compose down || true

      - name: Deploy new containers
        run: |
          docker-compose up -d

      - name: Verify containers are running
        run: docker ps -a
