name: Java CI 

on:
  repository_dispatch:
    types: [java-repo-update]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ecomm_store
        options: >-
          --health-cmd="mysqladmin ping -h 0.0.0.0 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
        with:
          repository: Sheldrake-Creator/Ecomm_Backend
          token: ${{ secrets.SERVER_PAT }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h 0.0.0.0 --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dspring-boot.run.profiles=ec2
  
      - name: Build Docker Image
        run: docker build -t sheldrakecreator/ecommrepo:server .
        env:
          DOCKER_BUILDKIT: 1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
      - name: Push Docker image
        run: docker push sheldrakecreator/ecommrepo:server
